'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const createUI=require('../admin-perrun-annul-ui');
const response=()=>({code:200,setHeader(){},status(n){this.code=n;return this;},json(v){this.body=v;return this;}});
function handler({authorized=true,error=null}={}){const calls=[];const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../lib/admin-perrun-annul.js'),'utf8'),{module,require:()=>({getServiceClient:()=>({rpc:async(name,args)=>{calls.push({name,args});return {data:{revision:1},error};}}),getAdminUser:async()=>authorized?{user:{id:'verified-uuid'},email:'verified@example.invalid'}:{error:'Forbidden',status:403}})});return {run:module.exports,calls};}
const payload={orderSessionId:'cs_local',expectedRevision:0,reason:'Participante solicitó anulación',confirm:true};
test('Annul HTTP binds actor to verified server JWT and only calls annul RPC',async()=>{const h=handler(),r=response();await h.run({method:'POST',body:payload},r);assert.equal(r.code,200);assert.equal(h.calls.length,1);assert.equal(h.calls[0].name,'admin_annul_perrun_participation');assert.equal(h.calls[0].args.p_admin_user_id,'verified-uuid');assert.equal(h.calls[0].args.p_admin_email,'verified@example.invalid');});
test('Annul HTTP rejects unauthorized before RPC',async()=>{const h=handler({authorized:false}),r=response();await h.run({method:'POST',body:payload},r);assert.equal(r.code,403);assert.equal(h.calls.length,0);});
for(const patch of [{confirm:false},{reason:''},{reason:'x'},{expectedRevision:-1},{expectedRevision:1.2},{adminUserId:'forged'},{payment_status:'refunded'},{bib_number:'005'},{production_number:1},{engraving_sequence:1}])test('Annul HTTP rejects malformed/injected '+JSON.stringify(patch),async()=>{const h=handler(),r=response();await h.run({method:'POST',body:{...payload,...patch}},r);assert.equal(r.code,400);assert.equal(h.calls.length,0);});
test('Annul revision conflict controlled; GET is forbidden',async()=>{const h=handler({error:{code:'P0001'}}),r=response();await h.run({method:'POST',body:payload},r);assert.equal(r.code,409);const r2=response();await h.run({method:'GET'},r2);assert.equal(r2.code,405);});
function uiFixture(){let shown=0,closed=0,refreshes=0;const sent=[],submit={disabled:false},cancel={},feedback={};const form={elements:{reason:{value:'Anulación solicitada'}},reportValidity:()=>true,querySelector:()=>submit};const dialog={setAttribute(){},addEventListener(){},showModal(){shown++;},close(){closed++;},querySelector:s=>s==='form'?form:s==='[data-cancel]'?cancel:feedback};const doc={createElement:t=>t==='dialog'?dialog:{},head:{appendChild(){}},body:{appendChild(){}},addEventListener(){}};
 const ui=createUI({document:doc,getToken:async()=>'mock-token',refresh:async()=>{refreshes++;},fetch:async(url,opts)=>{sent.push({url,opts});return {ok:true,json:async()=>opts.method==='GET'?{expectedRevision:4,registration:{registration_status:'active',full_name:'QA Person',bib_number:'004'}}:{ok:true}};}});return {ui,dialog,form,sent,submit,get shown(){return shown;},get closed(){return closed;},get refreshes(){return refreshes;}};}
test('Annul UI opens explicit confirmation, reason required, no write until submit',async()=>{const f=uiFixture();await f.ui.open('cs_local');assert.equal(f.shown,1);assert.equal(f.sent.length,1);assert.equal(f.sent[0].opts.method,'GET');assert.match(f.dialog.innerHTML,/Confirmar anulación/);assert.match(f.dialog.innerHTML,/No realiza ningún reembolso/);assert.match(f.dialog.innerHTML,/required minlength="3" maxlength="500"/);await f.form.onsubmit({preventDefault(){}});const sent=JSON.parse(f.sent[1].opts.body);assert.deepEqual(sent,{orderSessionId:'cs_local',expectedRevision:4,reason:'Anulación solicitada',confirm:true});assert.equal(f.closed,1);assert.equal(f.refreshes,1);});
test('Annul UI/source integration keeps history visible, readonly edit and active email guards',()=>{const html=fs.readFileSync(path.join(__dirname,'../admin-inscripciones.html'),'utf8');assert.match(html,/data-perrun-annul-order/);assert.match(html,/Participación anulada/);assert.match(html,/cancellation_reason/);for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g))if(!/src\s*=/.test(m[1]))new vm.Script(m[2]);const endpoint=fs.readFileSync(path.join(__dirname,'../api/resend-single-confirmation.js'),'utf8');assert.match(endpoint,/\.eq\('registration_status', 'active'\)/);const prod=fs.readFileSync(path.join(__dirname,'../admin-perrun-production-ui.js'),'utf8');assert.match(prod,/Participación anulada después de producción/);});
