'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {createRequire}=require('node:module'),{PGlite}=require('@electric-sql/pglite');
const distance=require('./helpers/perrun-admin-distance-fixture.cjs');
const f={...require('./helpers/perrun-admin-edit-cases.cjs'),edit:distance.edit,sql:distance.sql},{sqlAdapter}=require('./helpers/perrun-payment-sql-adapter.cjs');
const realAuth=require('../lib/_auth'),{authorizePerrunOrder}=require('../lib/_perrun-current-ownership');
const {createCheckoutSummaryClaim,COOKIE_NAME}=require('../lib/_checkout-summary-claim');
const {authorizedDog}=require('../lib/_perrun-engraving'),{sendPerrunConfirmation}=require('../lib/_perrun-confirmation');
const {enrichRegistrations,perrunCsv}=require('../lib/_perrun-operations');
process.env.ADMIN_EMAILS='admin@example.invalid';process.env.CHECKOUT_SUMMARY_SECRET='test-admin-ownership-secret-01234567890123456789';
let db;test.before(async()=>{db=new PGlite();await f.install(db);await distance.apply(db);});test.after(()=>db.close());
const res=()=>({statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}});
function client(){const c=sqlAdapter(db);c.auth={getUser:async token=>{const email={admin:'admin@example.invalid',old:'owner@example.invalid',current:'corrected@example.invalid',outsider:'stranger@example.invalid'}[token];return {data:{user:email?{id:f.actor,email}:null},error:email?null:{message:'invalid'}};}};const original=c.rpc;c.rpc=async(name,args)=>{
 if(name!=='admin_update_perrun_registration')return original(name,args);
 try{return {data:(await db.query(f.sql,distance.rpcKeys.map(k=>typeof args[k]==='object'?JSON.stringify(args[k]):args[k]))).rows[0].result};}catch(e){return {error:{code:e.code,message:e.message}};}
 };return c;}
function load(file,c){const filename=path.resolve(__dirname,'..',file),base=createRequire(filename),module={exports:{}};const auth={...realAuth,getServiceClient:()=>c,getAuthenticatedUser:req=>realAuth.getAuthenticatedUser(req,{supabase:c}),getAdminUser:(req,opts)=>realAuth.getAdminUser(req,{...opts,supabase:c})};
 vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module,exports:module.exports,require:name=>name.endsWith('_auth')?auth:name==='@supabase/supabase-js'?{createClient:()=>c}:name==='stripe'?()=>({checkout:{sessions:{retrieve(){throw Error('Stripe forbidden');}}}}):base(name),process,console:{log(){},error(){},warn(){}},URL},{filename});return module.exports;}
function body(x){return {orderSessionId:x.orderId,expectedRevision:0,distance:'3K',participant:x.participant,dogs:x.dogs.map(d=>({id:d.id,name:d.dog_name,weightKg:Number(d.weight_kg)})),reason:'Corrección de datos'};}
const req=(token,body,method='POST',query={})=>({method,headers:token?{authorization:'Bearer '+token}:{},body,query});
for(const token of [null,'bad','outsider'])test('Admin HTTP denies '+token+' before mutation',async()=>{const x=await f.fixture(db),before=await f.state(db,x),r=res();await load('lib/admin-perrun-registration.js',client())(req(token,body(x)),r);assert.equal(r.statusCode,token==='outsider'?403:401);assert.deepEqual(await f.state(db,x),before);});
test('Admin GET exposes current fields, readonly original contact and revision without mutations',async()=>{const x=await f.fixture(db),before=await f.state(db,x),r=res();await load('lib/admin-perrun-registration.js',client())(req('admin',null,'GET',{orderSessionId:x.orderId}),r);assert.equal(r.statusCode,200);assert.equal(r.body.expectedRevision,0);assert.equal(r.body.registration.dogs[0].engraving_sequence,x.dogs[0].engraving_sequence);assert.equal(r.body.order.owner_phone,x.participant.whatsapp);assert.deepEqual(await f.state(db,x),before);});
test('Admin POST uses verified JWT actor, updates current identity and never sends email',async()=>{const x=await f.fixture(db),r=res(),b=body(x);b.participant={...b.participant,email:'corrected@example.invalid'};await load('lib/admin-perrun-registration.js',client())(req('admin',b),r);assert.equal(r.statusCode,200);const s=await f.state(db,x);assert.equal(s.audit[0].admin_user_id,f.actor);assert.equal(s.audit[0].admin_email,'admin@example.invalid');assert.equal(s.human.confirmation_email_id,null);assert.equal(s.human.email_sent,false);});
for(const [field,value] of [['adminUserId','forged'],['distance','10K'],['amount',1]])test('Admin HTTP rejects body injection '+field,async()=>{const x=await f.fixture(db),r=res();await load('lib/admin-perrun-registration.js',client())(req('admin',{...body(x),[field]:value}),r);assert.equal(r.statusCode,400);assert.equal((await f.state(db,x)).audit.length,0);});
test('Admin HTTP stale revision maps to 409 with reload instruction',async()=>{const x=await f.fixture(db);await f.edit(db,x);const r=res();await load('lib/admin-perrun-registration.js',client())(req('admin',body(x)),r);assert.equal(r.statusCode,409);assert.match(r.body.error,/Recarga/);});
for(const value of ['1K','3K','5K'])test('Admin HTTP explicit root distance '+value+' accepted with JWT actor',async()=>{const x=await f.fixture(db),r=res();await load('lib/admin-perrun-registration.js',client())(req('admin',{...body(x),distance:value}),r);assert.equal(r.statusCode,200);const s=await f.state(db,x);assert.equal(s.human.distance,value);assert.equal(s.order.distance,'3K');assert.equal(s.order.admin_revision,1);assert.equal(s.audit[0].admin_user_id,f.actor);assert.equal(s.human.email_sent,false);});
for(const value of [undefined,null,'1k','10K','5K ',0,[],{}])test('Admin HTTP invalid distance '+JSON.stringify(value)+' 400 before RPC',async()=>{const x=await f.fixture(db),r=res(),c=client();let calls=0;c.rpc=async()=>{calls++;throw Error('Invalid distance must not reach SQL');};await load('lib/admin-perrun-registration.js',c)(req('admin',{...body(x),distance:value}),r);assert.equal(r.statusCode,400);assert.equal(calls,0);});
test('Admin rejects distance nested in participant',async()=>{const x=await f.fixture(db),b=body(x),r=res();b.participant={...b.participant,distance:'5K'};await load('lib/admin-perrun-registration.js',client())(req('admin',b),r);assert.equal(r.statusCode,400);});
test('Manual mocked resend renders corrected operational distance; save sends no email',async()=>{const x=await f.fixture(db),before=await f.state(db,x);await f.edit(db,x,{distance:'5K'});const current=await f.state(db,x);assert.equal(current.human.email_sent,false);assert.equal(current.human.confirmation_email_id,null);assert.equal(current.order.distance,before.order.distance);const sent=[];const result=await sendPerrunConfirmation({supabase:client(),sessionId:x.orderId,resendRequestId:crypto.randomUUID(),mockProvider:{emails:{send:async payload=>{sent.push(payload);return {data:{id:'mock_distance_reemail'}};}}}});assert.equal(result.ok,true);assert.equal(sent.length,1);assert.match(sent[0].text,/Distancia: 5K/);assert.match(sent[0].html,/5K/);assert.doesNotMatch(sent[0].text,/Distancia: 3K/);});
test('Updated email transfers profile visibility without changing Supabase Auth',async()=>{const x=await f.fixture(db);await f.edit(db,x,{participant:{email:'corrected@example.invalid'}});const handler=load('lib/me-registrations.js',client());const old=res(),current=res();await handler(req('old',null,'GET'),old);await handler(req('current',null,'GET'),current);assert.equal(old.statusCode,200);assert.ok(!old.body.registrations.some(r=>r.id===x.dogs[0].registration_id));assert.ok(current.body.registrations.some(r=>r.id===x.dogs[0].registration_id));});
test('Manual reemail uses corrected recipient and current dog names, transport is mock only',async()=>{const x=await f.fixture(db);await f.edit(db,x,{participant:{email:'corrected@example.invalid'},dogs:x.dogs.map(d=>({id:d.id,name:'Corrected Dog',weightKg:20}))});const sends=[];const result=await sendPerrunConfirmation({supabase:client(),sessionId:x.orderId,resendRequestId:crypto.randomUUID(),mockProvider:{emails:{send:async payload=>{sends.push(payload);return {data:{id:'mock_admin_reemail'}};}}}});assert.equal(result.ok,true);assert.equal(sends.length,1);assert.equal(sends[0].to,'corrected@example.invalid');assert.match(sends[0].text,/Corrected Dog/);});
test('CSV contact reflects current phone but plate snapshot stays historical',async()=>{const x=await f.fixture(db);await db.query("update public.registration_dogs set plate_status='preparing' where id=$1",[x.dogs[0].id]);await f.edit(db,x,{participant:{whatsapp:'+525587654321'}});const h=(await db.query('select * from public.inscripciones where order_session_id=$1',[x.orderId])).rows;const enriched=await enrichRegistrations(client(),h),csv=perrunCsv(enriched);assert.equal(enriched[0].owner_phone,'+525587654321');assert.equal(enriched[0].dogs[0].owner_phone_for_plate,x.participant.whatsapp);assert.match(csv,/525587654321/);assert.match(csv,/525512345678/);});
test('Old cookie works before email edit; afterwards cookie and old JWT cannot access dogs',async()=>{const x=await f.fixture(db),c=client(),cookie=COOKIE_NAME+'='+createCheckoutSummaryClaim(x.orderId).claim;const oldReq={headers:{cookie}};assert.equal(await authorizePerrunOrder(oldReq,c,x.orderId),true);await f.edit(db,x,{participant:{email:'corrected@example.invalid'}});assert.equal(await authorizePerrunOrder(oldReq,c,x.orderId),false);assert.equal(await authorizePerrunOrder(req('old'),c,x.orderId),false);assert.equal(await authorizePerrunOrder(req('current'),c,x.orderId),true);await assert.rejects(authorizedDog({req:oldReq,supabase:c,order:x.orderId,index:1}),/not_authorized/);await assert.rejects(authorizedDog({req:req('old'),supabase:c,order:x.orderId,index:1}),/not_authorized/);assert.equal((await authorizedDog({req:req('current'),supabase:c,order:x.orderId,index:1})).dog.id,x.dogs[0].id);});
test('Summary revocation cannot be bypassed by omitting event; current JWT sees corrected email',async()=>{const x=await f.fixture(db),c=client(),cookie=COOKIE_NAME+'='+createCheckoutSummaryClaim(x.orderId).claim;await f.edit(db,x,{participant:{email:'corrected@example.invalid'}});const handler=load('api/checkout-summary.js',c);for(const query of [{session_id:x.orderId,event:'perrun-2027'},{session_id:x.orderId}]){const r=res();await handler({method:'GET',headers:{cookie},query},r);assert.equal(r.statusCode,403);assert.ok(!r.body.participants);}const r=res();await handler(req('current',null,'GET',{session_id:x.orderId,event:'perrun-2027'}),r);assert.equal(r.statusCode,200);assert.equal(r.body.email,'corrected@example.invalid');});
test('Legacy archive explicitly denies Perrun even an otherwise archivable LIVE row',async()=>{const x=await f.fixture(db),c=client();const orig=c.from;c.from=table=>{if(table!=='inscripciones')return orig(table);const q={select(){return q;},eq(){return q;},single:async()=>({data:{event_slug:'perrun-2027',registration_status:'active',payment_status:'pending',order_session_id:'cs_live_mock',stripe_session_id:'cs_live_mock',bib_number:null}})};return q;};const r=res();await load('lib/admin-archive-attempt.js',c)(req('admin',{inscriptionId:x.dogs[0].registration_id,email:'owner@example.invalid',reason:'Test'}),r);assert.equal(r.statusCode,409);assert.match(r.body.error,/Perrun/);});
test('UI and source inline scripts parse; readonly controls, reason and dedicated handler are present',()=>{new vm.Script(fs.readFileSync(path.join(__dirname,'../admin-perrun-edit-ui.js'),'utf8'));const html=fs.readFileSync(path.join(__dirname,'../admin-inscripciones.html'),'utf8');for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g))if(!/src\s*=/.test(m[1]))new vm.Script(m[2]);assert.match(html,/data-perrun-edit-order/);const source=fs.readFileSync(path.join(__dirname,'../admin-perrun-edit-ui.js'),'utf8');assert.match(source,/expectedRevision/);assert.match(source,/Cambiar el correo también cambia qué cuenta/);assert.match(source,/plate_started_at/);assert.match(source,/Motivo de corrección/);assert.match(source,/admin-perrun-registration/);});
