'use strict';
const test=require('node:test'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');
const {PGlite}=require('@electric-sql/pglite'),{installFixture}=require('./helpers/perrun-schema-fixture.cjs'),{cases}=require('./helpers/perrun-engraving-flow-contract.cjs');
const root=path.resolve(__dirname,'..');let db;process.env.STRIPE_SECRET_KEY='sk_test_engraving_fixture';delete process.env.VERCEL_ENV;process.env.CHECKOUT_SUMMARY_SECRET=process.env.CHECKOUT_SUMMARY_SECRET||'fixture_checkout_summary_secret_32_characters';
test.before(async()=>{db=new PGlite();await installFixture(db,root);for(const name of ['20261001055227_perrun_phase1_model.sql','20261001113351_perrun_payment_state.sql','20261001162118_perrun_engraving_payment_persistence.sql'])await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',name),'utf8'));});test.after(()=>db.close());
for(const c of cases)test(c.name,()=>c.run(db));
test('6 browser CTA keeps price/IDs server-owned and escapes content',async()=>{const c={globalThis:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'perrun-engraving-ui.js'),'utf8'),c);const ui=c.globalThis.KineticHubEngraving;assert.equal(ui.button('cs',1,false),'');assert.ok(!ui.button('<img>',1,true).includes('<img>'));assert.match(ui.button('cs',1,true),/Pagar grabado — \$35 MXN/)});
test('6 browser action posts main session and dog index only',async()=>{let request,url;const message={},button={disabled:false,dataset:{engravingOrder:'cs_test_main',engravingDogIndex:'2'},parentElement:{querySelector:()=>message}};const root={location:{pathname:'/succes.html',assign:v=>url=v},fetch:async(path,options)=>{request={path,options};return {ok:true,json:async()=>({url:'https://checkout.stripe.com/c/pay/test'})}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../perrun-engraving-ui.js'),'utf8'),{globalThis:root,URL});await root.KineticHubEngraving.pay(button);assert.deepEqual(JSON.parse(request.options.body),{flow:'perrun-engraving-v1',orderSessionId:'cs_test_main',dogIndex:2});assert.equal(url,'https://checkout.stripe.com/c/pay/test')});
test('6 all changed inline/browser scripts parse',()=>{for(const file of ['succes.html','perfil.html'])for(const s of fs.readFileSync(path.join(root,file),'utf8').matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g))if(!/src\s*=/.test(s[1]))new vm.Script(s[2]);for(const file of ['script.js','perrun-engraving-ui.js'])new vm.Script(fs.readFileSync(path.join(root,file),'utf8'))});
