'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createRequire}=require('node:module');const {Readable}=require('node:stream');
const {PGlite}=require('@electric-sql/pglite');
const {installFixture}=require('./helpers/perrun-schema-fixture.cjs');
const {sqlAdapter}=require('./helpers/perrun-payment-sql-adapter.cjs');
const payment=require('../lib/_perrun-payment');
const checkout=require('../lib/_perrun-checkout');
const root=path.resolve(__dirname,'..');
process.env.STRIPE_SECRET_KEY='sk_test_phase4_fixture';delete process.env.VERCEL_ENV;
const human={fullName:'Webhook Owner',shirtSize:'M',birthDate:'1990-01-01',whatsapp:'+525500000000',state:'Ciudad de México',borough:'Gustavo A. Madero'};
const dog={name:'Luna',weightKg:10,engravingRequested:true};
const metadata={event_slug:'perrun-2027',flow_version:'perrun_v1',ticket_count:'1',order_ref:'11111111-2222-4333-8444-555555555555'};
let db,next=0;
async function fixture({count=1,distance='3K',requested=true}={}){
  const id='cs_test_phase4_'+(++next),calls=[];
  await db.query('select public.prepare_perrun_order($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7::timestamptz)',[id,distance,'owner@example.invalid',JSON.stringify(human),JSON.stringify(Array.from({length:count},(_,i)=>({...dog,name:i?'Sol':'Luna',engravingRequested:requested}))),'presale','2026-10-01T12:00:00-06:00']);
  const session={id,mode:'payment',livemode:false,payment_status:'paid',amount_total:45000+(count-1)*18000,currency:'mxn',payment_intent:'pi_'+id,metadata:{...metadata}};
  const supabase=sqlAdapter(db,calls),state={session,calls,supabase,retrieveCalls:[],sends:0,meta:0};
  const stripe={checkout:{sessions:{retrieve:async id=>{state.retrieveCalls.push(id);if(state.retrieveError)throw Error('network');return structuredClone(state.session);},list:async()=>({data:[structuredClone(state.session)]})}},charges:{retrieve:async()=>{if(state.chargeError)throw Error('network');return state.charge;}}};
  function event(type='checkout.session.completed',changes={}){return {id:'evt_'+(++next),type,livemode:false,data:{object:{...structuredClone(session),...changes}}};}
  async function run(e){return payment.handlePerrunPayment({stripe,supabase:state.supabase,event:e});}
  async function row(table='perrun_checkout_orders'){return (await db.query('select * from public.'+table+' where order_session_id=$1',[id])).rows;}
  return {...state,state,stripe,event,run,row,id};
}
function loadWebhook(f,e,signatureError=false){
  const filename=path.join(root,'api/stripe-webhook.js'),realRequire=createRequire(filename),module={exports:{}};
  f.stripe.webhooks={constructEvent:()=>{if(signatureError)throw Error('invalid fixture signature');return e;}};
  const requireMock=name=>name==='stripe'?()=>f.stripe:name==='@supabase/supabase-js'?{createClient:()=>f.state.supabase}:name==='resend'?{Resend:class{constructor(){this.emails={send:async()=>{f.state.sends++;if(f.state.emailError)return{error:{message:'fake provider failure'}};return{data:{id:'fake'}};}};}}}:name.includes('_perrun-confirmation')?{sendPerrunConfirmation:args=>realRequire(name).sendPerrunConfirmation({...args,qa:false,mockProvider:args.resend})}:name.includes('_meta-capi')?{trackMetaEvent:async()=>{f.state.meta++;return{ok:true};}}:realRequire(name);
  vm.runInNewContext(fs.readFileSync(filename,'utf8'),{require:requireMock,module,exports:module.exports,process,Buffer,console:{log(){},warn(){},error(){}},setTimeout,clearTimeout},{filename});
  return module.exports;
}
async function api(f,e,signatureError=false){
  const req=Readable.from([Buffer.from(JSON.stringify(e))]);req.method='POST';req.headers={'stripe-signature':'fixture'};
  const res={statusCode:200,status(n){this.statusCode=n;return this;},json(b){this.body=b;return this;},send(b){this.body=b;return this;}};
  await loadWebhook(f,e,signatureError)(req,res);return res;
}
async function count(id){return (await db.query('select count(*)::int n from public.registration_dogs where order_session_id=$1',[id])).rows[0].n;}
async function counter(){return (await db.query('select last_sequence from public.perrun_paid_dog_counter')).rows[0].last_sequence;}
test.before(async()=>{db=new PGlite();await installFixture(db);for(const file of ['20261001055227_perrun_phase1_model.sql','20261001113351_perrun_payment_state.sql'])await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',file),'utf8'));});
test.after(async()=>{await db.close();});
for(const distance of ['1K','3K','5K'])for(const dogs of [1,2])test('Perrun '+distance+' '+dogs+' dogs: real finalizer creates one human, Perrun email and no CAPI',async()=>{
  const f=await fixture({distance,count:dogs}),r=await api(f,f.event());assert.equal(r.statusCode,200);assert.equal(r.body.finalized,true);
  const humans=await f.row('inscripciones'),registered=await f.row('registration_dogs');assert.equal(humans.length,1);assert.equal(humans[0].event_slug,'perrun-2027');assert.equal(humans[0].distance,distance);assert.equal(humans[0].ticket_count,1);assert.equal(humans[0].ticket_index,1);assert.ok(humans[0].bib_number);assert.equal(registered.length,dogs);assert.equal(f.calls[0].name,'finalize_perrun_paid_order');assert.equal(f.state.sends,1);assert.equal(humans[0].email_sent,true);assert.equal(f.state.meta,0);
});
for(const type of ['checkout.session.completed','checkout.session.async_payment_succeeded'])test(type+' duplicate with real SQL keeps identical dogs/BIB/counter',async()=>{
  const f=await fixture({count:2}),e=f.event(type);await f.run(e);const rows=await f.row('registration_dogs'),humans=await f.row('inscripciones'),n=await counter();await f.run(e);await f.run(f.event(type));assert.deepEqual(await f.row('registration_dogs'),rows);assert.deepEqual(await f.row('inscripciones'),humans);assert.equal(await counter(),n);
});
for(const first of ['checkout.session.completed','checkout.session.async_payment_succeeded'])test('Mixed paid events '+first+' first finalizes once',async()=>{
  const f=await fixture({count:2}),other=first==='checkout.session.completed'?'checkout.session.async_payment_succeeded':'checkout.session.completed';await f.run(f.event(first));const n=await counter(),rows=await f.row('registration_dogs');await f.run(f.event(other));assert.equal(await counter(),n);assert.deepEqual(await f.row('registration_dogs'),rows);
});
for(const retrievedStatus of ['unpaid','paid'])test('OXXO completed unpaid snapshot; current Stripe '+retrievedStatus+' still does not fulfill',async()=>{
  const f=await fixture({count:2});f.state.session.payment_status=retrievedStatus;const n=await counter();const r=await f.run(f.event('checkout.session.completed',{payment_status:'unpaid'}));assert.equal(r.status,200);assert.equal((await f.row())[0].payment_status,'pending');assert.equal(await count(f.id),0);assert.equal((await f.row('inscripciones')).length,0);assert.equal(await counter(),n);assert.deepEqual(f.calls.map(x=>x.name),['record_perrun_payment_state']);
});
test('OXXO pending then async success finalizes using exact confirmed price',async()=>{const f=await fixture();f.state.session.payment_status='unpaid';await f.run(f.event('checkout.session.completed',{payment_status:'unpaid'}));f.state.session.payment_status='paid';assert.equal((await f.run(f.event('checkout.session.async_payment_succeeded'))).status,200);assert.equal((await f.row())[0].payment_status,'paid');assert.equal(await count(f.id),1);});
test('OXXO failure and late unpaid completion preserve failed state and consume zero positions',async()=>{const f=await fixture({count:2});f.state.session.payment_status='unpaid';const n=await counter();await f.run(f.event('checkout.session.async_payment_failed',{payment_status:'unpaid'}));await f.run(f.event('checkout.session.completed',{payment_status:'unpaid'}));assert.equal((await f.row())[0].payment_status,'failed');assert.equal(await count(f.id),0);assert.equal(await counter(),n);assert.equal((await f.row())[0].payment_intent_id,null);});
test('Late failed event never downgrades paid or creates allocations',async()=>{const f=await fixture();await f.run(f.event());const n=await counter(),rows=await f.row();await f.run(f.event('checkout.session.async_payment_failed'));assert.deepEqual(await f.row(),rows);assert.equal(await counter(),n);});
test('Legitimate success after failed state is supported by real RPC',async()=>{const f=await fixture();await f.run(f.event('checkout.session.async_payment_failed'));await f.run(f.event('checkout.session.async_payment_succeeded'));assert.equal((await f.row())[0].payment_status,'paid');assert.equal(await count(f.id),1);});
for(const [name,change] of Object.entries({amount:s=>s.amount_total++,currency:s=>s.currency='usd',version:s=>s.metadata.flow_version='wrong',event:s=>s.metadata.event_slug='axolote-night-run',ticket:s=>s.metadata.ticket_count='2',nonce:s=>s.metadata.order_ref='bad',live:s=>s.livemode=true,mode:s=>s.mode='subscription',identity:s=>s.id='cs_other',paymentIntent:s=>s.payment_intent='pi_different'}))test('Authoritative '+name+' mismatch never finalizes',async()=>{const f=await fixture(),e=f.event(),n=await counter();change(f.state.session);const r=await f.run(e);assert.equal(r.status,200);assert.equal(r.body.rejected,true);assert.equal(await count(f.id),0);assert.equal(await counter(),n);assert.equal(f.calls.length,0);});
for(const [name,change] of Object.entries({amount:s=>s.amount_total++,currency:s=>s.currency='usd',metadata:s=>s.metadata={...s.metadata,order_ref:'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'},live:s=>s.livemode=true}))test('Signed snapshot '+name+' mismatch rejected before fulfillment',async()=>{const f=await fixture(),e=f.event();change(e.data.object);const r=await f.run(e);assert.equal(r.status,200);assert.equal(r.body.rejected,true);assert.equal(f.calls.length,0);});
for(const removed of ['event_slug','flow_version','both'])test('Corrupted Perrun metadata '+removed+' routes by draft and cannot become Axolote',async()=>{const f=await fixture(),e=f.event();if(removed==='both')e.data.object.metadata={};else delete e.data.object.metadata[removed];const r=await api(f,e);assert.equal(r.statusCode,200);assert.equal(r.body.flow,'perrun');assert.equal(r.body.rejected,true);assert.equal(f.calls.length,0);assert.equal(f.state.sends,0);});
test('Signature verification precedes all reads/RPCs',async()=>{const f=await fixture();assert.equal((await api(f,f.event(),true)).statusCode,400);assert.equal(f.calls.length,0);assert.equal(f.state.retrieveCalls.length,0);});
test('Stripe network error returns retryable 503 and no writes',async()=>{const f=await fixture();f.state.retrieveError=true;assert.equal((await f.run(f.event())).status,503);assert.equal(f.calls.length,0);});
test('Paid delivery not yet confirmed by authoritative Stripe retries without writes',async()=>{const f=await fixture();f.state.session.payment_status='unpaid';assert.equal((await f.run(f.event('checkout.session.async_payment_succeeded'))).status,503);assert.equal(f.calls.length,0);});
test('Missing prepared draft retries rather than losing paid event',async()=>{const f=await fixture();await db.query('delete from public.perrun_checkout_orders where order_session_id=$1',[f.id]);assert.equal((await f.run(f.event())).status,503);assert.equal(f.calls.length,0);});
for(const source of ['read','rpc'])test('Transient '+source+' failure retries safely',async()=>{const f=await fixture();if(source==='read')f.state.supabase={...f.supabase,from(){const q={select(){return q;},eq(){return q;},maybeSingle:async()=>({error:{code:'57014'},data:null})};return q;}};else f.state.supabase={...f.supabase,rpc:async()=>({error:{code:'57014'},data:null})};assert.equal((await payment.handlePerrunPayment({stripe:f.stripe,supabase:f.state.supabase,event:f.event()})).status,503);assert.equal(await count(f.id),0);});
for(const env of ['live_key','production'])test('Perrun '+env+' blocked before Stripe retrieval',async()=>{const f=await fixture(),key=process.env.STRIPE_SECRET_KEY;if(env==='live_key')process.env.STRIPE_SECRET_KEY='sk_live_fixture';else process.env.VERCEL_ENV='production';try{assert.equal((await f.run(f.event())).status,503);assert.equal(f.state.retrieveCalls.length,0);}finally{process.env.STRIPE_SECRET_KEY=key;delete process.env.VERCEL_ENV;}});
test('Paid expanded PaymentIntent id is resolved without creating another ticket',async()=>{const f=await fixture();f.state.session.payment_intent={id:f.session.payment_intent};assert.equal((await f.run(f.event())).status,200);assert.equal(await count(f.id),1);});
test('Boundary positions 299,300,301 are historical; only <=300 free and unrequested paid position costs zero',async()=>{
  await db.exec('update public.perrun_paid_dog_counter set last_sequence=298');const one=await fixture({count:2}),two=await fixture({requested:false});await one.run(one.event());await two.run(two.event());const rows=[...await one.row('registration_dogs'),...await two.row('registration_dogs')].sort((a,b)=>a.engraving_sequence-b.engraving_sequence);assert.deepEqual(rows.map(r=>Number(r.engraving_sequence)),[299,300,301]);assert.deepEqual(rows.map(r=>r.engraving_free),[true,true,false]);assert.deepEqual(rows.map(r=>r.engraving_payment_amount_cents),[0,0,0]);
});
test('Position >300 requested engraving is 3500 cents, no automatic add-on checkout',async()=>{const f=await fixture();await f.run(f.event());const r=(await f.row('registration_dogs'))[0];assert.equal(r.engraving_free,false);assert.equal(r.engraving_payment_required,true);assert.equal(r.engraving_payment_amount_cents,3500);assert.equal((await db.query('select count(*)::int n from public.perrun_engraving_payments')).rows[0].n,0);});
for(const type of ['charge.refunded','refund.created','refund.updated'])for(const expanded of [false,true])test(type+' '+(expanded?'expanded':'string')+' identity: refund preserves positions/dogs and duplicate paid delivery cannot reactivate',async()=>{
  const f=await fixture({count:2});await f.run(f.event());const rows=await f.row('registration_dogs'),n=await counter();const pi=expanded?{id:f.session.payment_intent}:f.session.payment_intent;
  f.state.charge={id:'ch_fixture',amount:f.session.amount_total,amount_refunded:f.session.amount_total,payment_intent:pi};
  const object=type==='charge.refunded'?f.state.charge:{id:'re_fixture',status:'succeeded',amount:f.session.amount_total,payment_intent:pi,charge:expanded?f.state.charge:'ch_fixture'};
  const e={id:'evt_refund_'+(++next),type,livemode:false,data:{object}};
  assert.equal((await api(f,e)).statusCode,200);assert.equal((await api(f,e)).statusCode,200);assert.equal((await f.row('inscripciones'))[0].payment_status,'refunded');await f.run(f.event());assert.equal((await f.row('inscripciones'))[0].payment_status,'refunded');assert.deepEqual(await f.row('registration_dogs'),rows);assert.equal(await counter(),n);assert.equal((await f.row())[0].payment_status,'paid');
});
for(const type of ['refund.created','refund.updated'])test(type+' await fix falls back to expanded charge when refund has no PaymentIntent',async()=>{const f=await fixture();await f.run(f.event());f.state.charge={id:'ch_fallback',amount:45000,payment_intent:{id:f.session.payment_intent}};const e={id:'evt_fallback',type,data:{object:{id:'re_fallback',status:'succeeded',amount:45000,charge:'ch_fallback'}}};const r=await api(f,e);assert.equal(r.statusCode,200);assert.equal((await f.row('inscripciones'))[0].payment_status,'refunded');});
for(const type of ['charge.refunded','refund.updated'])test(type+' partial refund leaves human paid and allocations unchanged',async()=>{const f=await fixture();await f.run(f.event());const n=await counter();f.state.charge={id:'ch_partial',amount:45000,amount_refunded:1000,payment_intent:f.session.payment_intent};const object=type==='charge.refunded'?f.state.charge:{id:'re_partial',status:'succeeded',amount:1000,payment_intent:f.session.payment_intent,charge:f.state.charge};assert.equal((await api(f,{id:'evt_partial',type,data:{object}})).statusCode,200);assert.equal((await f.row('inscripciones'))[0].payment_status,'paid');assert.equal(await counter(),n);});
test('Refund before paid webhook retries, then applies after successful finalization',async()=>{const f=await fixture();const e={id:'evt_early_refund',type:'charge.refunded',data:{object:{id:'ch_early',amount:45000,amount_refunded:45000,payment_intent:f.session.payment_intent}}};assert.equal((await api(f,e)).statusCode,503);await f.run(f.event());assert.equal((await api(f,e)).statusCode,200);assert.equal((await f.row('inscripciones'))[0].payment_status,'refunded');});
test('Perrun refund transient update error retries',async()=>{const f=await fixture();await f.run(f.event());const base=f.supabase;f.state.supabase={...base,from(t){if(t!=='inscripciones')return base.from(t);const q={update(){return q;},eq(){return q;},in(){return q;},select:async()=>({data:null,error:{code:'57014'}})};return {select:cols=>base.from(t).select(cols),update:()=>q};}};const e={id:'evt_update_error',type:'charge.refunded',data:{object:{id:'ch_update',amount:45000,amount_refunded:45000,payment_intent:f.session.payment_intent}}};assert.equal((await api(f,e)).statusCode,503);assert.equal((await f.row('inscripciones'))[0].payment_status,'paid');});

for(const status of ['prepared','pending','failed'])test('Authoritative Perrun summary '+status+' exposes no BIB/positions/phone',async()=>{
  const f=await fixture({count:2});if(status!=='prepared')await f.run(f.event(status==='pending'?'checkout.session.completed':'checkout.session.async_payment_failed',{payment_status:'unpaid'}));
  const s=await checkout.getPerrunSummary(f.supabase,f.id);assert.equal(s.payment_status,status==='failed'?'payment_failed':'pending');assert.equal(s.bib_number,null);assert.equal(s.dogCount,2);assert.equal(s.draftState,status);assert.ok(s.dogs.every(d=>d.engravingSequence===undefined));assert.equal(JSON.stringify(s).includes('525500000000'),false);
});
test('Paid summary uses actual single BIB, dogs and confirmed engraving amounts',async()=>{
  const f=await fixture({count:2});await f.run(f.event());const s=await checkout.getPerrunSummary(f.supabase,f.id),h=(await f.row('inscripciones'))[0];assert.equal(s.payment_status,'paid');assert.equal(s.ticketCount,1);assert.equal(s.bib_number,h.bib_number);assert.equal(s.participants[0].bibNumber,h.bib_number);assert.equal(s.dogs.length,2);assert.equal(s.total,630);assert.ok(s.dogs.every(d=>d.engravingSequence));assert.equal(JSON.stringify(s).includes('525500000000'),false);
});
test('Refund summary reflects human cancellation and retains historical positions',async()=>{
  const f=await fixture();await f.run(f.event());const before=await checkout.getPerrunSummary(f.supabase,f.id);await payment.handlePerrunRefund({stripe:f.stripe,supabase:f.supabase,sessionId:f.id,paymentIntentId:f.session.payment_intent});const after=await checkout.getPerrunSummary(f.supabase,f.id);assert.equal(after.payment_status,'refunded');assert.equal(after.bib_number,before.bib_number);assert.equal(after.dogs[0].engravingSequence,before.dogs[0].engravingSequence);assert.match(after.dogs[0].engravingStatus,/histórica/);
});
test('Incomplete finalized summary fails closed rather than inventing pending/paid data',async()=>{
  const f=await fixture();await f.run(f.event());const base=f.supabase;const mock={...base,from(t){if(t!=='registration_dogs')return base.from(t);const q={select(){return q;},eq(){return q;},order:async()=>({data:[],error:null})};return q;}};await assert.rejects(checkout.getPerrunSummary(mock,f.id),/incompleto/);
});
for(const status of ['paid','pending','payment_failed','refunded'])test('Perrun UI '+status+' hides legacy waiver/profile/email promises',()=>{
  const html=fs.readFileSync(path.join(root,'succes.html'),'utf8'),script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('function applySummaryState'));
  const start=script.indexOf('    function applySummaryState'),end=script.indexOf('    function renderParticipants',start);const source=script.slice(start,end);
  const elements=new Map();const document={getElementById(id){if(!elements.has(id))elements.set(id,{style:{}});return elements.get(id);}};
  const context={document,escapeHtml:s=>String(s),summary:{eventSlug:'perrun-2027',distance:'3K',payment_status:status}};vm.runInNewContext(source+'\napplySummaryState(summary);',context);
  for(const id of ['documentBlock','profileBlock','emailNotice'])assert.equal(elements.get(id).style.display,'none');assert.doesNotMatch(elements.get('statusCopy').textContent,/correo|exoneración|perfil/);assert.equal(elements.get('retryPaymentLink').style.display,status==='payment_failed'?'inline-block':'none');
});
for(const type of ['refund.created','refund.updated'])test(type+' failed charge lookup returns 503 instead of silently losing refund',async()=>{const f=await fixture();await f.run(f.event());f.state.chargeError=true;const e={id:'evt_charge_lookup',type,data:{object:{id:'re_lookup',status:'succeeded',amount:45000,payment_intent:f.session.payment_intent,charge:'ch_lookup'}}};const r=await api(f,e);assert.equal(r.statusCode,503);assert.equal((await f.row('inscripciones'))[0].payment_status,'paid');});
test('PaymentIntent failure resolved through TEST session only records failed state',async()=>{const f=await fixture();const r=await api(f,{id:'evt_pi_failure',type:'payment_intent.payment_failed',livemode:false,data:{object:{id:f.session.payment_intent,metadata:{}}}});assert.equal(r.statusCode,200);assert.equal((await f.row())[0].payment_status,'failed');assert.equal(await count(f.id),0);});
test('Invalid Perrun draft event or malformed dog count is rejected without a mutation',async()=>{const f=await fixture();const draft=(await f.row())[0];for(const override of [{event_slug:'cascanueces-run'},{dogs:[]},{distance:'10K'}]){const r=await payment.handlePerrunPayment({stripe:f.stripe,supabase:f.supabase,event:f.event(),draft:{...draft,...override}});assert.equal(r.status,200);assert.equal(r.body.rejected,true);}assert.equal(f.calls.length,0);});
test('Permanent payment identity conflict gets a controlled ACK and preserves ledger',async()=>{const f=await fixture();await f.run(f.event());const n=await counter();f.state.session.payment_intent='pi_second_identity';const e=f.event();e.data.object.payment_intent='pi_second_identity';const r=await f.run(e);assert.equal(r.status,200);assert.equal(r.body.rejected,true);assert.equal(await counter(),n);assert.equal((await f.row())[0].payment_intent_id,'pi_'+f.id);});
test('Missing paid PaymentIntent waits for authoritative Stripe instead of allocating',async()=>{const f=await fixture();f.state.session.payment_intent=null;const e=f.event();e.data.object.payment_intent=null;assert.equal((await f.run(e)).status,503);assert.equal(f.calls.length,0);});

test('PaymentIntent failed with stripped Perrun metadata is rejected by draft routing, never legacy',async()=>{const f=await fixture();f.state.session.metadata={};const r=await api(f,{id:'evt_pi_corrupt',type:'payment_intent.payment_failed',data:{object:{id:f.session.payment_intent,metadata:{}}}});assert.equal(r.statusCode,200);assert.equal(r.body.flow,'perrun');assert.equal(r.body.rejected,true);assert.equal((await f.row())[0].payment_status,'prepared');assert.equal(f.calls.length,0);});
test('Refund waits if finalized human row is not readable; no false successful acknowledgment',async()=>{const f=await fixture();await f.run(f.event());const base=f.supabase;const supabase={...base,from(t){if(t!=='inscripciones')return base.from(t);const q={select(){return q;},eq(){return q;},maybeSingle:async()=>({data:null,error:null})};return q;}};const r=await payment.handlePerrunRefund({stripe:f.stripe,supabase,sessionId:f.id,paymentIntentId:f.session.payment_intent});assert.equal(r.status,503);assert.equal((await f.row('inscripciones'))[0].payment_status,'paid');});
test('Invalid event id cannot call the payment-state RPC',async()=>{const f=await fixture(),e=f.event('checkout.session.async_payment_failed');e.id='evt.bad';const r=await f.run(e);assert.equal(r.status,200);assert.equal(r.body.rejected,true);assert.equal(f.calls.length,0);});
test('Refund missing historical payment identity gets controlled rejection and no mutation',async()=>{const f=await fixture();await f.run(f.event());const r=await payment.handlePerrunRefund({stripe:f.stripe,supabase:f.supabase,sessionId:f.id,paymentIntentId:'pi_another'});assert.equal(r.status,200);assert.equal(r.body.rejected,true);assert.equal((await f.row('inscripciones'))[0].payment_status,'paid');});

for(const type of ['charge.refunded','refund.created','refund.updated'])test(type+' Perrun metadata routes to refunds rather than generic ignored-event guard',async()=>{const f=await fixture();await f.run(f.event());f.state.charge={id:'ch_meta',amount:45000,amount_refunded:45000,payment_intent:f.session.payment_intent,metadata:{event_slug:'perrun-2027'}};const object=type==='charge.refunded'?f.state.charge:{id:'re_meta',status:'succeeded',amount:45000,payment_intent:f.session.payment_intent,charge:f.state.charge,metadata:{event_slug:'perrun-2027'}};const r=await api(f,{id:'evt_meta_refund',type,data:{object}});assert.equal(r.statusCode,200);assert.equal(r.body.refunded,true);assert.equal((await f.row('inscripciones'))[0].payment_status,'refunded');});
test('Refund before finalization with stripped metadata routes by draft identity and is rejected safely',async()=>{const f=await fixture();f.state.session.metadata={};const e={id:'evt_refund_stripped',type:'charge.refunded',data:{object:{id:'ch_stripped',amount:45000,amount_refunded:45000,payment_intent:f.session.payment_intent}}};const r=await api(f,e);assert.equal(r.statusCode,200);assert.equal(r.body.flow,'perrun');assert.equal(r.body.rejected,true);assert.equal((await f.row('inscripciones')).length,0);});

test('Paid duplicate webhook sends one Perrun confirmation and preserves dogs/BIB',async()=>{
  const f=await fixture({count:2});const e=f.event();assert.equal((await api(f,e)).statusCode,200);const ledger=await f.row('registration_dogs'),human=await f.row('inscripciones'),n=await counter();
  assert.equal((await api(f,f.event('checkout.session.async_payment_succeeded'))).statusCode,200);assert.equal(f.state.sends,1);assert.deepEqual(await f.row('registration_dogs'),ledger);assert.deepEqual(await f.row('inscripciones'),human);assert.equal(await counter(),n);
});
test('OXXO unpaid and failure webhooks never send confirmation',async()=>{const f=await fixture();f.state.session.payment_status='unpaid';await api(f,f.event('checkout.session.completed',{payment_status:'unpaid'}));await api(f,f.event('checkout.session.async_payment_failed',{payment_status:'unpaid'}));assert.equal(f.state.sends,0);assert.equal((await f.row('inscripciones')).length,0);});
test('Refund then paid retry never sends a paid confirmation for cancelled human',async()=>{const f=await fixture();await f.run(f.event());assert.equal((await payment.handlePerrunRefund({stripe:f.stripe,supabase:f.supabase,sessionId:f.id,paymentIntentId:f.session.payment_intent})).status,200);const r=await api(f,f.event());assert.equal(r.statusCode,200);assert.equal(f.state.sends,0);assert.equal((await f.row('inscripciones'))[0].registration_status,'cancelled');});

test('Webhook email provider error returns retryable 503 without repeating finalization allocation',async()=>{
 const f=await fixture({count:2});f.state.emailError=true;const first=await api(f,f.event());assert.equal(first.statusCode,503);assert.equal(first.body.email_pending,true);const ledger=await f.row('registration_dogs'),human=await f.row('inscripciones'),n=await counter();assert.equal(human[0].email_sent,false);
 f.state.emailError=false;const retry=await api(f,f.event('checkout.session.async_payment_succeeded'));assert.equal(retry.statusCode,200);assert.deepEqual(await f.row('registration_dogs'),ledger);assert.equal(await counter(),n);const after=await f.row('inscripciones');assert.equal(after[0].bib_number,human[0].bib_number);assert.equal(after.length,1);assert.equal(after[0].email_sent,true);assert.equal(f.state.meta,0);
});

test('OXXO pending then paid async success sends exactly one confirmation',async()=>{const f=await fixture();f.state.session.payment_status='unpaid';await api(f,f.event('checkout.session.completed',{payment_status:'unpaid'}));assert.equal(f.state.sends,0);f.state.session.payment_status='paid';const e=f.event('checkout.session.async_payment_succeeded');assert.equal((await api(f,e)).statusCode,200);assert.equal(f.state.sends,1);assert.equal((await api(f,e)).statusCode,200);assert.equal(f.state.sends,1);});
