'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm');
const create=require('../admin-perrun-production-ui');
const sample=()=>{const id=crypto.randomUUID(),batch=crypto.randomUUID();const snapshot={schema_version:1,registration_id:id,bib_number:'004',participant:{name:'Historical Name',shirt_size:'M',distance:'3K'},dogs:[{name:'Dog',weight_kg:8,category:'S',engraving_sequence:301,plate_status:'not_started'}],dog_count:1};return {summary:{pending:1,produced:0,closed_batches:0},candidates:[snapshot],batches:[],batch:null,items:[],id,batchId:batch,snapshot};};
function fixture(){const handlers={},root={classList:{add(){}},innerHTML:'',addEventListener(k,fn){handlers[k]=fn;},querySelectorAll(){return [];}};const document={head:{appendChild(){}},createElement(){return {};}};let confirm=true,state=sample(),downloaded,calls=[];
 const ui=create({document,root,getToken:async()=> 'mock_admin',uuid:()=>state.batchId,confirm:()=>confirm,download:(blob,id)=>{downloaded={blob,id};},fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>state,blob:async()=>new Blob(['frozen csv'])};}});
 return {ui,root,handlers,calls,get state(){return state;},set state(x){state=x;},get downloaded(){return downloaded;},set confirm(x){confirm=x;},select(id,checked=true){handlers.change({target:{dataset:{registration:id},checked}});}};
}
test('Production section separated, scripts parse and creates no batch on initial load',async()=>{const x=fixture();assert.equal(x.calls.length,0);assert.match(x.root.innerHTML,/Cargar producción/);await x.ui.act('load');assert.equal(x.calls[0].options.method,'GET');assert.match(x.root.innerHTML,/Se asignará al cerrar/);const html=fs.readFileSync(require('node:path').join(__dirname,'../admin-inscripciones.html'),'utf8');assert.match(html,/Producción Perrun/);assert.match(html,/createPerrunProductionUI/);new vm.Script(fs.readFileSync(require('node:path').join(__dirname,'../admin-perrun-production-ui.js'),'utf8'));});
test('Candidate review selection creates draft without numbers or trusted actor in browser payload',async()=>{const x=fixture();x.ui.accept(x.state);x.select(x.state.id);await x.ui.act('save');const b=JSON.parse(x.calls[0].options.body);assert.deepEqual(b.registrationIds,[x.state.id]);assert.equal(b.expectedRevision,null);assert.equal(b.operation,'save');assert.equal(b.batchId,x.state.batchId);assert.deepEqual(Object.keys(b).sort(),['batchId','expectedRevision','operation','registrationIds']);});
test('Close cancellation creates no request; explicit confirmation sends revision only',async()=>{const x=fixture();x.state={...x.state,batch:{id:x.state.batchId,status:'draft',revision:2,item_count:1},items:[{registration_id:x.state.id,bib_number:'004',preview:x.state.snapshot,production_number:null}]};x.ui.accept(x.state);x.confirm=false;await x.ui.act('close');assert.equal(x.calls.length,0);x.confirm=true;await x.ui.act('close');const body=JSON.parse(x.calls[0].options.body);assert.equal(body.confirm,true);assert.equal(body.expectedRevision,2);assert.equal(body.registrationIds,undefined);assert.match(x.ui.warning,/definitivos/);});
test('Changed draft selection disables close until saved; production no editable field',()=>{const x=fixture();x.state={...x.state,batch:{id:x.state.batchId,status:'draft',revision:0,item_count:1},items:[{registration_id:x.state.id,preview:x.state.snapshot,bib_number:'004'}]};x.ui.accept(x.state);x.select(x.state.id,false);assert.match(x.root.innerHTML,/Guarda la selección/);assert.match(x.root.innerHTML,/data-production="close" disabled/);assert.doesNotMatch(x.root.innerHTML,/input[^>]*production_number/);});
test('Closed panel uses only immutable snapshot; CSV downloaded from authenticated endpoint',async()=>{const x=fixture();x.state={...x.state,batch:{id:x.state.batchId,status:'closed',closed_at:'2026-10-03T00:00:00Z',item_count:1},candidates:[{...x.state.snapshot,participant:{name:'Current Changed'}}],items:[{registration_id:x.state.id,bib_number:'004',production_number:1,snapshot:{...x.state.snapshot,production_number:1}}]};x.ui.accept(x.state);assert.match(x.root.innerHTML,/Historical Name/);assert.doesNotMatch(x.root.innerHTML,/Current Changed|data-production="close"|data-production="save"/);await x.ui.act('export');assert.match(x.calls[0].url,/format=csv/);assert.equal(x.calls[0].options.headers.Authorization,'Bearer mock_admin');assert.equal(await x.downloaded.blob.text(),'frozen csv');});
test('Names escaped, expired auth/request errors visible without hidden fallback',async()=>{const x=fixture();x.state.snapshot.participant.name='<script>danger</script>';x.ui.accept(x.state);assert.ok(!x.root.innerHTML.includes('<script>danger'));assert.ok(x.root.innerHTML.includes('&lt;script&gt;'));const root={classList:{add(){}},addEventListener(){},querySelectorAll:()=>[]};const ui=create({document:{head:{appendChild(){}},createElement:()=>({})},root,getToken:async()=>null,fetch:async()=>{throw Error('Must not call');},confirm:()=>true});await ui.act('load');assert.match(root.innerHTML,/Sesión no válida/);});
