'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const create=require('../admin-perrun-edit-ui');
function fixture({source='stripe',plate='preparing',started='2026-10-02T12:00:00Z',payment='pending'}={}){
 const field=()=>({value:'',addEventListener(){}});const elements=Object.fromEntries(['state','borough','dogWeight0','dogCategory0','fullName','email','shirtSize','birthDate','whatsapp','reason','dogName0'].map(k=>[k,field()]));elements.state.value='Jalisco';elements.borough.disabled=true;
 const submit={disabled:false},cancel={},feedback={};const form={elements,reportValidity:()=>true,querySelector:()=>submit};
 const dialog={setAttribute(){},addEventListener(){},close(){},querySelector:s=>s==='form'?form:s==='[data-cancel]'?cancel:feedback};const style={};const doc={body:{appendChild(){}},head:{appendChild(){}},createElement:t=>t==='dialog'?dialog:style,addEventListener(){}};let sent;
 const ui=create({document:doc,getToken:async()=> 'synthetic',refresh:async()=>{},fetch:async(url,options)=>{sent=JSON.parse(options.body);return {ok:true,json:async()=>({ok:true})};},catalog:{STATES:['Jalisco'],CDMX_BOROUGHS:[],isCdmxState:()=>false},event:{categoryForWeight:()=> 'S'}});
 const data={expectedRevision:2,order:{order_session_id:'cs_test_ui',payment_source:source,owner_phone:'+525512345678'},registration:{bib_number:'004',distance:'3K',amount_paid:450,full_name:'Test Owner',email:'test@example.invalid',shirt_size:'M',birth_date:'1995-02-28',whatsapp:'+525512345678',state:'Jalisco',borough:null,dogs:[{id:'dog-fixture',dog_name:'Luna',weight_kg:8,category:'S',plate_status:plate,plate_started_at:started,engraving_sequence:301,engraving_requested:true,engraving_free:false,engraving_payment_required:true,engraving_payment_status:payment,engraving_status:'Grabado solicitado · Pago pendiente $35 MXN',dog_name_for_plate:'Luna',owner_phone_for_plate:'+525512345678'}]}};
 ui.render(data);return {dialog,style,form,elements,data,ui,get sent(){return sent;}};
}
test('Readonly data render as wrapping outputs with explicit label; category remains readonly',()=>{const x=fixture();assert.match(x.dialog.innerHTML,/Solo lectura/);assert.match(x.dialog.innerHTML,/<output class="readonly" aria-label="Estado de grabado">Grabado solicitado · Pago pendiente \$35 MXN<\/output>/);assert.match(x.dialog.innerHTML,/name="dogCategory0"[^>]*readonly/);assert.match(x.style.textContent,/white-space:normal/);assert.match(x.style.textContent,/overflow-wrap:anywhere/);assert.match(x.style.textContent,/cursor:not-allowed/);});
for(const [source,label] of [['stripe','Stripe'],['manual_transfer','Transferencia']])test('Payment source presentation '+source,()=>{const x=fixture({source});assert.ok(x.dialog.innerHTML.includes('aria-label="Origen de pago">'+label+'</output>'));assert.equal(x.data.order.payment_source,source);});
for(const [plate,label] of [['preparing','En preparación'],['engraved','Grabada'],['not_started','No iniciada'],['skipped','Omitida']])test('Plate presentation '+plate,()=>{const x=fixture({plate});assert.ok(x.dialog.innerHTML.includes('aria-label="Estado de placa">'+label+'</output>'));assert.equal(x.data.registration.dogs[0].plate_status,plate);});
for(const [payment,label] of [['free','Gratis'],['pending','Pendiente'],['paid','Pagado'],['refunded','Reembolsado']])test('Engraving payment presentation '+payment,()=>{const x=fixture({payment});assert.ok(x.dialog.innerHTML.includes('aria-label="Pago de grabado">'+label+'</output>'));assert.equal(x.data.registration.dogs[0].engraving_payment_status,payment);});
for(const [plate,started] of [['preparing',null],['engraved',null],['not_started','2026-10-02T12:00:00Z']])test('Locked dog name visibly disabled '+plate+' '+started,()=>{const x=fixture({plate,started});assert.match(x.dialog.innerHTML,/name="dogName0"[^>]*disabled/);assert.ok(x.dialog.innerHTML.includes('Este dato ya no puede modificarse porque la placa entró a producción.'));assert.match(x.style.textContent,/input:disabled/);});
test('Unstarted dog name remains editable',()=>{const x=fixture({plate:'not_started',started:null});assert.doesNotMatch(x.dialog.innerHTML.match(/<input name="dogName0"[^>]*>/)[0],/disabled|readonly/);});
test('Plate timestamp uses Spanish date and Mexico City time without raw ISO; reason has requested placeholder',()=>{const x=fixture();assert.ok(x.dialog.innerHTML.includes(new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Mexico_City'}).format(new Date('2026-10-02T12:00:00Z'))));assert.ok(!x.dialog.innerHTML.includes('2026-10-02T12:00:00Z'));assert.match(x.dialog.innerHTML,/placeholder="Ej. Corrección solicitada por el participante"/);assert.equal(x.data.registration.dogs[0].plate_started_at,'2026-10-02T12:00:00Z');});
test('Presentation never adds enums or readonly data to correction payload, DOB stays ISO',async()=>{const x=fixture();Object.assign(x.elements.birthDate,{value:'1995-02-28'});x.elements.reason.value='Corrección ficticia';x.elements.dogWeight0.value='8';await x.form.onsubmit({preventDefault(){}});assert.equal(x.sent.participant.birthDate,'1995-02-28');assert.equal(x.sent.dogs[0].name,'Luna');assert.deepEqual(Object.keys(x.sent.dogs[0]).sort(),['id','name','weightKg']);assert.deepEqual(Object.keys(x.sent).sort(),['dogs','expectedRevision','orderSessionId','participant','reason']);});
test('Closed production shows all readonly fields and exact warning; corrections never send production data',async()=>{const x=fixture();Object.assign(x.data.registration,{production_status:'closed',production_number:3,production_batch_id:'immutable-batch'});x.ui.render(x.data);assert.match(x.dialog.innerHTML,/<legend>Producción<\/legend>/);assert.ok(x.dialog.innerHTML.includes('aria-label="Estado de producción">Producción cerrada</output>'));assert.ok(x.dialog.innerHTML.includes('aria-label="Lote">immutable-batch</output>'));assert.match(x.dialog.innerHTML,/aria-label="Número de producción">003<\/output>/);assert.ok(x.dialog.innerHTML.includes('Esta inscripción ya pertenece a un lote de producción cerrado. Las correcciones actuales no modificarán los datos que ya fueron enviados a producción.'));assert.doesNotMatch(x.dialog.innerHTML,/name="production_number"|name="production_batch_id"|name="production_status"/);x.elements.dogWeight0.value='8';x.elements.reason.value='Corrección ficticia';await x.form.onsubmit({preventDefault(){}});assert.equal(x.sent.production_number,undefined);assert.equal(x.sent.production_batch_id,undefined);assert.equal(x.sent.production_status,undefined);});
for(const [status,label] of [['not_produced','Pendiente de producción'],['not_available','No disponible']])test('Production '+status+' always shows three readonly fields without closed warning',()=>{const x=fixture();Object.assign(x.data.registration,{production_status:status,production_number:null,production_batch_id:null});x.ui.render(x.data);const section=x.dialog.innerHTML.match(/<fieldset><legend>Producción<\/legend>(.*?)<\/fieldset>/)[1];assert.equal((section.match(/<output class="readonly"/g)||[]).length,3);assert.ok(section.includes('aria-label="Estado de producción">'+label+'</output>'));for(const field of ['Lote','Número de producción'])assert.ok(section.includes('aria-label="'+field+'">—</output>'));assert.doesNotMatch(section,/<input|<select|<textarea/);assert.doesNotMatch(x.dialog.innerHTML,/Esta inscripción ya pertenece a un lote de producción cerrado/);});
