'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function fixture(count=1,total=450,options={}) {
 const nodes=new Map(),calls=[],dialogs=[],storage=new Map();
 const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',checked:false,textContent:'',hidden:false,addEventListener(){},querySelectorAll(){return[];}});return nodes.get(id);};
 const quote={pricingModelVersion:2,baseAmount:450,secondDogFee:count===2?180:0,engravingAmount:total-(count===2?630:450),total,currency:'MXN',ticketCount:1,dogCount:count,reservationId:'reservation_same',quoteToken:'token_same',benefits:Array.from({length:count},(_,i)=>({dogIndex:i+1,free:i< count-(total-(count===2?630:450))/35,engravingRequested:true,surcharge:i< count-(total-(count===2?630:450))/35?0:35})),...options.quote};
 const document={getElementById:node,body:{appendChild(){}},createElement(){const buttons=new Map();const dialog={innerHTML:'',events:{},setAttribute(){},addEventListener(t,f){this.events[t]=f;},querySelector(s){if(!buttons.has(s))buttons.set(s,{focus(){}});return buttons.get(s);},showModal(){dialogs.push(this);},close(){this.closed=true;},remove(){this.removed=true;}};return dialog;}};
 const context={document,TextEncoder,crypto:crypto.webcrypto,KineticHubPerrunEvent:require('../perrun-event-data'),localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},confirm(){throw Error('Native confirmation prohibited');},fetch:async(url,opts)=>{const body=JSON.parse(opts.body);calls.push(body);if(options.error)return {ok:false,json:async()=>({error:'Unavailable'})};return {ok:true,json:async()=>body.action==='quote'?quote:{url:'https://checkout.stripe.com/c/pay/mock_only',total,...options.result}};}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../perrun-checkout.js'),'utf8'),context);
 const api=context.KineticHubPerrunCheckout.create({form:{addEventListener(){}},onChange(){}});
 node('perrunAddDog').checked=count===2;for(let i=1;i<=count;i++){node('perrunDogName'+i).value='QA Dog '+i;node('perrunDogWeight'+i).value='8';node('perrunEngraving'+i).checked=true;}
 api.updateSummary(450);
 const submit=()=>api.submit({eventSlug:'perrun-2027',distance:'3K'});
 return {api,node,submit,calls,dialogs,quote,options};
}
async function opened(f){for(let i=0;i<100&&!f.dialogs.length;i++)await new Promise(r=>setTimeout(r,2));assert.equal(f.dialogs.length>0,true);return f.dialogs.at(-1);}
for(const [count,total] of [[1,450],[2,630]])test('V2 unchanged '+total+' auto continues without confirmation',async()=>{const f=fixture(count,total);const result=await f.submit();assert.match(result.url,/checkout.stripe.com/);assert.equal(f.dialogs.length,0);assert.deepEqual(f.calls.map(c=>c.action),['quote','create']);assert.equal(f.node('perrunEngravingPrice').textContent,'Beneficio gratuito reservado');});
for(const [count,total,charge] of [[1,485,35],[2,665,35],[2,700,70]])test('V2 increase '+total+' requires own dialog before create',async()=>{const f=fixture(count,total),pending=f.submit(),d=await opened(f);assert.deepEqual(f.calls.map(c=>c.action),['quote']);assert.match(d.innerHTML,new RegExp('Aceptar y pagar \\$'+total+' MXN'));assert.equal(f.node('totalPrice').textContent,'$'+total+' MXN');assert.equal(f.node('perrunEngravingPrice').textContent,'$'+charge+' MXN');assert.match(d.innerHTML,/El total cambió/);d.querySelector('[data-price-accept]').onclick();const result=await pending;assert.match(result.url,/checkout.stripe.com/);assert.deepEqual(f.calls.map(c=>c.action),['quote','create']);assert.equal(f.calls[1].reservationId,'reservation_same');assert.equal(f.calls[1].quoteToken,'token_same');});
for(const cancel of ['back','escape'])test('V2 '+cancel+' creates no session and retry still requires acceptance on same reservation',async()=>{const f=fixture(2,665),pending=f.submit(),d=await opened(f);if(cancel==='back')d.querySelector('[data-price-back]').onclick();else d.events.cancel({preventDefault(){}});assert.equal((await pending).cancelled,true);assert.equal(f.calls.length,1);const retry=f.submit();while(f.dialogs.length<2)await new Promise(r=>setTimeout(r,2));f.dialogs[1].querySelector('[data-price-accept]').onclick();await retry;assert.deepEqual(f.calls.map(c=>c.action),['quote','create']);assert.equal(f.calls[1].reservationId,'reservation_same');});
test('V2 lower total auto continues with authoritative summary',async()=>{const f=fixture(1,400,{quote:{baseAmount:400,engravingAmount:0,benefits:[{dogIndex:1,free:true,engravingRequested:true,surcharge:0}]}});await f.submit();assert.equal(f.dialogs.length,0);assert.equal(f.node('totalPrice').textContent,'$400 MXN');});
test('Backend error prevents create/redirect',async()=>{const f=fixture(1,450,{error:true});await assert.rejects(f.submit(),/Unavailable/);assert.equal(f.calls.length,1);});
for(const quote of [{total:451},{total:NaN},{currency:'USD'},{dogCount:2},{benefits:[]},{benefits:[{dogIndex:1,free:true,engravingRequested:true,surcharge:35}]},{total:'450'}])test('V2 rejects inconsistent quote '+JSON.stringify(quote),async()=>{const f=fixture(1,450,{quote});await assert.rejects(f.submit(),/inconsistente/);assert.equal(f.calls.length,1);assert.equal(f.dialogs.length,0);});
test('V2 inconsistent create amount never returns redirect',async()=>{const f=fixture(1,450,{result:{total:485}});await assert.rejects(f.submit(),/inconsistente/);});
test('V2 create failure retries same accepted reservation without new quote',async()=>{const f=fixture(1,485),pending=f.submit(),d=await opened(f);f.options.result={total:999};d.querySelector('[data-price-accept]').onclick();await assert.rejects(pending,/inconsistente/);f.options.result={};await f.submit();assert.deepEqual(f.calls.map(c=>c.action),['quote','create','create']);assert.equal(f.calls[1].reservationId,f.calls[2].reservationId);assert.equal(f.dialogs.length,1);});
test('V2 acceptance dialog is accessible and fits mobile/desktop without fixed width',()=>{const html=fs.readFileSync(require.resolve('../checkout.html'),'utf8'),js=fs.readFileSync(require.resolve('../perrun-checkout.js'),'utf8');assert.match(html,/width: min\(540px, calc\(100% - 32px\)\)/);assert.match(html,/min-height: 44px/);assert.match(js,/aria-labelledby/);assert.match(js,/showModal\(\)/);assert.match(js,/data-price-back.*focus\(\)/);assert.doesNotMatch(js,/root\.confirm\('Inscripción:/);});
test('V1 remains direct without V2 dialog',async()=>{const f=fixture(1,450,{quote:{pricingModelVersion:undefined,engravingAmount:undefined}});await f.submit();assert.equal(f.dialogs.length,0);assert.deepEqual(f.calls.map(c=>c.action),['quote','create']);});
