"use strict";
const test=require('node:test'),assert=require('node:assert/strict');
const {sendTransactionalEmail,FROM}=require('../lib/_transactional-email');
const engraving=require('../lib/_perrun-engraving');
function provider(){const calls=[];return {calls,emails:{async send(payload,options){calls.push({payload,options});return {data:{id:'fixture_provider_receipt'}};}}};}
async function mode(value,fn){const old=process.env.PERRUN_QA_LOCAL;try{if(value===undefined)delete process.env.PERRUN_QA_LOCAL;else process.env.PERRUN_QA_LOCAL=value;await fn();}finally{if(old===undefined)delete process.env.PERRUN_QA_LOCAL;else process.env.PERRUN_QA_LOCAL=old;}}
test('Outside QA shares existing Resend sender and stable key',()=>mode(undefined,async()=>{const resend=provider();await sendTransactionalEmail({resend,payload:{to:'fixture@example.invalid',subject:'fixture'},idempotencyKey:'stable'});assert.equal(resend.calls.length,1);assert.equal(resend.calls[0].payload.from,FROM);assert.equal(resend.calls[0].options.idempotencyKey,'stable');}));
test('Outside QA missing Resend fails closed, never fabricated receipt',()=>mode(undefined,async()=>{await assert.rejects(sendTransactionalEmail({payload:{},idempotencyKey:'stable',mockId:'mock'}),/unavailable/);}));
test('QA blocks injected real transport even when available',()=>mode('1',async()=>{const resend=provider();const sent=await sendTransactionalEmail({resend,payload:{},idempotencyKey:'stable',mockId:'mock_fixture'});assert.equal(sent.data.id,'mock_fixture');assert.equal(resend.calls.length,0);}));
test('QA allows explicit controlled mock only',()=>mode('1',async()=>{const resend=provider(),mockProvider=provider();await sendTransactionalEmail({resend,mockProvider,payload:{},idempotencyKey:'stable'});assert.equal(resend.calls.length,0);assert.equal(mockProvider.calls.length,1);}));
function fixture(){const resend=provider(),marks=[],human={email:'fixture@example.invalid'};const supabase={from(){const q={select(){return q;},eq(){return q;},async maybeSingle(){return {data:human};}};return q;},async rpc(name,args){marks.push({name,args});return {data:{id:'payment_fixture'}};}};return {resend,marks,supabase,dog:{registration_id:'human_fixture',registration_email:human.email,dog_name:'Luna'},payment:{id:'payment_fixture',status:'paid'}};}
test('Paid engraving uses real-path client and marks existing RPC receipt',()=>mode(undefined,async()=>{const f=fixture();await engraving.confirmEmail(f);assert.equal(f.resend.calls.length,1);assert.match(f.resend.calls[0].payload.text,/Pago de grabado: [$]35 MXN/);assert.equal(f.marks[0].name,'mark_perrun_engraving_email_sent');assert.equal(f.marks[0].args.p_provider_id,'fixture_provider_receipt');f.payment.confirmation_email_sent_at='2026-10-01';await engraving.confirmEmail(f);assert.equal(f.resend.calls.length,1);}));
for(const status of ['pending','failed','refunded'])test('Engraving '+status+' sends no confirmation',()=>mode(undefined,async()=>{const f=fixture();f.payment.status=status;await engraving.confirmEmail(f);assert.equal(f.resend.calls.length,0);assert.equal(f.marks.length,0);}));
test('Engraving provider failure leaves receipt unmarked',()=>mode(undefined,async()=>{const f=fixture();f.resend.emails.send=async()=>({error:{message:'fixture failure'}});await assert.rejects(engraving.confirmEmail(f),/engraving_email_failed/);assert.equal(f.marks.length,0);}));
