'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {createRequire}=require('node:module');
const {spawnSync}=require('node:child_process');
const event=require('../perrun-event-data');
const stages=require('../perrun-stage-config');
const catalog=require('../event-catalog');
const root=path.resolve(__dirname,'..');
for(const [date,key,price,open] of [
 ['2026-10-31T23:59:59-06:00','presale',450,true],
 ['2026-10-31T23:59:59.999-06:00','presale',450,true],
 ['2026-11-01T00:00:00-06:00','general',500,true],
 ['2026-12-31T23:59:59-06:00','general',500,true],
 ['2027-01-01T00:00:00-06:00','late',550,true],
 ['2027-01-25T15:59:59-06:00','late',550,true],
 ['2027-01-25T15:59:59.999-06:00','late',550,true],
 ['2027-01-25T16:00:00-06:00','closed',null,false],
 ['2027-01-25T16:00:00.001-06:00','closed',null,false]
])test('Perrun stage boundary '+date,()=>{const s=stages.getPerrunStageByDate(date);assert.equal(s.key,key);assert.equal(s.amount,price);assert.equal(s.isOpen,open);assert.equal(s.status,open?'OPEN':'CLOSED');});
test('Perrun uses absolute timestamps and the same stage catalog reference',()=>{assert.equal(event.pricing.stages,stages.PERRUN_STAGE_CATALOG);assert.equal(event.timeZone,'America/Mexico_City');assert.throws(()=>stages.getPerrunStageByDate('2027-01-25T16:00:00'));assert.throws(()=>stages.getPerrunStageByDate('invalid'));assert.equal(stages.getPerrunStageByDate('2027-01-25T22:00:00Z').isOpen,false);});
test('Perrun boundaries do not depend on host timezone',()=>{const results=['UTC','America/Los_Angeles','Asia/Tokyo'].map(TZ=>{const r=spawnSync(process.execPath,['-e',"console.log(require('./perrun-stage-config').getPerrunStageByDate('2026-11-01T06:00:00Z').key)"],{cwd:root,env:{...process.env,TZ},encoding:'utf8'});assert.equal(r.status,0);return r.stdout.trim();});assert.deepEqual(results,['general','general','general']);});
for(const distance of ['1K','3K','5K'])test('Perrun explicitly resolves distance '+distance,()=>{const selected=catalog.resolveEventSelection(event.slug,distance);assert.equal(selected.slug,event.slug);assert.equal(selected.distance,distance);assert.equal(event.validateDistance(distance),distance);});
test('Perrun rejects invalid and missing distance without 5K fallback',()=>{for(const distance of ['','10K','Axolote',null]){assert.equal(catalog.resolveEventSelection(event.slug,distance),null);assert.throws(()=>event.validateDistance(distance));}assert.equal(catalog.resolveEvent('missing'),null);});
test('S/M permit two dogs',()=>{assert.deepEqual(event.validateDogWeights([3,25]),['S','M']);});
test('L/XL permit only one dog',()=>{assert.deepEqual(event.validateDogWeights([50]),['L']);assert.deepEqual(event.validateDogWeights([80]),['XL']);for(const weights of [[50,80],[80,50]])assert.throws(()=>event.validateDogWeights(weights));});
test('Mixed two-dog groups with L/XL are rejected in both orders',()=>{for(const weights of [[3,26],[26,3],[80,25],[25,80]])assert.throws(()=>event.validateDogWeights(weights));});
test('Perrun constants represent second dog and engraving without browser eligibility',()=>{assert.equal(event.dogRules.secondDogFee,180);assert.equal(event.dogRules.engravingPaidPrice,35);assert.equal(event.dogRules.freeEngravingLimit,300);assert.equal(event.engravingOutcome,undefined);});
test('Confirmed event content has no invented start times',()=>{assert.equal(event.date.iso,'2027-02-14');assert.equal(event.location.name,'Bosque de San Juan de Aragón');assert.equal(event.awards,false);assert.equal(event.recreational,true);assert.deepEqual(event.dogKit,['Bandana','Servicio veterinario','Placa conmemorativa']);assert.deepEqual(event.humanKit,['Número','Playera']);assert.equal(event.pickup.date,'2027-02-12');assert.equal(event.pickup.start,'10:00');assert.equal(event.pickup.end,'16:00');assert.equal(event.time,undefined);assert.equal(event.modalities,undefined);});
test('Axolote resolver retains its identity and stage provider',()=>{const s=catalog.resolveEventSelection('axolote-night-run');assert.equal(s.slug,'axolote-night-run');assert.equal(s.distance,'5K');assert.equal(s.getStage,require('../axolote-stage-config').getAxoloteStageByDate);assert.equal(s.checkoutEnabled,true);});
test('Cascanueces resolver retains distances and stage provider',()=>{const s=catalog.resolveEventSelection('cascanueces-run','10K');assert.equal(s.slug,'cascanueces-run');assert.equal(s.distance,'10K');assert.equal(s.getStage,require('../cascanueces-stage-config').getCascanuecesStageByDate);assert.equal(s.priceEnvironmentVariables.acceso_general,'STRIPE_CASCANUECES_GENERAL_PRICE_ID');assert.equal(s.checkoutEnabled,true);});
function browser(){const context={Date,URLSearchParams,window:null};context.window=context;vm.createContext(context);for(const f of ['axolote-stage-config.js','cascanueces-stage-config.js','perrun-stage-config.js','perrun-event-data.js','event-catalog.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context);return context;}
test('Browser and Node share Perrun stage and event resolution',()=>{const c=browser();assert.equal(c.KineticHubEventCatalog.resolveEventSelection('perrun-2027','1K').slug,event.slug);assert.equal(c.KineticHubPerrunStageConfig.getPerrunStageByDate('2027-01-01T00:00:00-06:00').amount,550);});
test('Legacy checkout page redirects Perrun without changing slug or calling Stripe',()=>{const c=browser();let redirected; c.location={search:'?event=perrun-2027&distance=1K',replace:value=>{redirected=value;}};c.document={addEventListener:()=>{throw Error('Legacy checkout must not initialize');}};const html=fs.readFileSync(path.join(root,'checkout.html'),'utf8');const inline=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const checkoutParams'));assert.ok(inline);assert.throws(()=>vm.runInContext(inline,c),/Checkout unavailable/);assert.equal(c.KineticHubCheckoutSelection.eventSlug,event.slug);assert.equal(c.KineticHubCheckoutSelection.distance,'1K');assert.equal(c.KineticHubCheckoutSelection.checkoutEnabled,false);assert.equal(redirected,'eventos.html');});
test('Legacy API recognizes Perrun but cannot create a Stripe session',async()=>{const file=path.join(root,'api/create-checkout-session.js');const localRequire=createRequire(file);let stripeCalls=0;const context={process:{env:{STRIPE_SECRET_KEY:'sk_test_fixture',SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'fixture'}},console,module:{exports:{}},require:id=>{if(id==='stripe')return ()=>({checkout:{sessions:{create:()=>{stripeCalls++;throw Error('Forbidden');}}}});if(id==='@supabase/supabase-js')return {createClient:()=>({})};if(id==='../lib/_rate-limit')return {enforceRateLimit:async()=>null};return localRequire(id);}};vm.runInNewContext(fs.readFileSync(file,'utf8'),context,{filename:file});const res={code:null,body:null,status(n){this.code=n;return this;},json(b){this.body=b;return this;},setHeader(){}};await context.module.exports({method:'POST',headers:{},body:{eventSlug:event.slug,distance:'1K',email:'fixture@example.invalid'}},res);assert.equal(res.code,400);assert.match(res.body.error,/Perrun.*habilitado/);assert.equal(stripeCalls,0);});
test('Frozen event configuration cannot acquire mutable dates or prices',()=>{assert.ok(Object.isFrozen(event));assert.ok(Object.isFrozen(event.pricing.stages));assert.ok(Object.isFrozen(event.dogRules.categories));assert.throws(()=>{event.dogRules.secondDogFee=0;});});

test('Browser scripts parse as browser programs and generated counterpart stays synchronized',()=>{for(const file of ['script.js','script.min.js','perrun-stage-config.js','perrun-event-data.js','event-catalog.js'])assert.doesNotThrow(()=>new vm.Script(fs.readFileSync(path.join(root,file),'utf8')));assert.equal(fs.readFileSync(path.join(root,'script.js'),'utf8'),fs.readFileSync(path.join(root,'script.min.js'),'utf8'));});

test('Profile resolver retains Perrun identity and never invents a missing 5K',()=>{const c=browser();const source=fs.readFileSync(path.join(root,'script.js'),'utf8');const start=source.indexOf('const PROFILE_EVENT_CATALOG =');const end=source.indexOf('const formatStatus =',start);assert.ok(start>0&&end>start);vm.runInContext(source.slice(start,end)+"globalThis.profileEvent=getProfileEvent('perrun-2027');globalThis.missingDistance=getDistance({event_slug:'perrun-2027'});globalThis.oneK=getDistance({event_slug:'perrun-2027',distance:'1K'});",c);assert.equal(c.profileEvent.name,event.name);assert.equal(c.profileEvent.waiverUrl,null);assert.equal(c.profileEvent.announcementUrl,null);assert.equal(c.missingDistance,'Por confirmar');assert.equal(c.oneK,'1K');});
test('Event catalog card renders only confirmed shared Perrun metadata',()=>{const c=browser();const nodes=new Map();const card={dataset:{},querySelector(selector){if(!nodes.has(selector))nodes.set(selector,{});return nodes.get(selector);}};c.document={getElementById:id=>{assert.equal(id,'perrunCatalogCard');return card;}};const html=fs.readFileSync(path.join(root,'eventos.html'),'utf8');const inline=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const perrunCatalogEvent'));vm.runInContext(inline,c);assert.equal(card.dataset.eventSlug,event.slug);assert.equal(nodes.get('[data-perrun-name]').textContent,event.name);assert.match(nodes.get('[data-perrun-distances]').textContent,/1K \/ 3K \/ 5K/);assert.match(nodes.get('[data-perrun-date-location]').textContent,/14 de febrero de 2027/);});
test('Disabled Perrun checkout does not initialize the legacy form',()=>{const source=fs.readFileSync(path.join(root,'script.js'),'utf8');const prefix=source.slice(source.indexOf('\nfunction setupCheckoutForm() {')+1,source.indexOf('const CHECKOUT_EMAIL_KEY',source.indexOf('\nfunction setupCheckoutForm() {')+1));const c={window:{KineticHubCheckoutSelection:{checkoutEnabled:false}},document:{getElementById:()=>{throw Error('Form must not initialize');}}};vm.runInNewContext(prefix+'} setupCheckoutForm();',c);});
