'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {createRequire}=require('node:module'),{PGlite}=require('@electric-sql/pglite');
const f=require('./helpers/perrun-production-fixture.cjs'),{sqlAdapter}=require('./helpers/perrun-payment-sql-adapter.cjs'),auth=require('../lib/_auth');
process.env.ADMIN_EMAILS='admin@example.invalid';
let db;test.before(async()=>{db=new PGlite();await f.install(db);});test.after(()=>db?.close());test.beforeEach(()=>f.reset(db));
function client(){const c=sqlAdapter(db);c.auth={getUser:async token=>({data:{user:token==='admin'?{id:f.actor,email:f.email}:token==='user'?{id:crypto.randomUUID(),email:'participant@example.invalid'}:null},error:null})};
 const old=c.rpc;c.rpc=async(name,args)=>{const specs={admin_read_perrun_production:['p_batch_id'],admin_save_perrun_production_batch:['p_batch_id','p_expected_revision','p_registration_ids','p_admin_user_id','p_admin_email'],admin_close_perrun_production_batch:['p_batch_id','p_expected_revision','p_admin_user_id','p_admin_email']};if(!specs[name])return old(name,args);try{return {data:(await db.query('select public.'+name+'('+specs[name].map((_,i)=>'$'+(i+1)).join(',')+') result',specs[name].map(k=>args[k]))).rows[0].result,error:null};}catch(e){return {error:{message:e.message,code:e.code}};}};return c;}
function load(file,c){const filename=path.resolve(__dirname,'..',file),base=createRequire(filename),module={exports:{}};vm.runInNewContext(fs.readFileSync(filename,'utf8'),{module,exports:module.exports,require:name=>name.endsWith('_auth')?{...auth,getServiceClient:()=>c}:base(name),process,console,URL},{filename});return module.exports;}
const response=()=>({code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(body){this.body=body;return this;},send(body){this.body=body;return this;}});
async function run({token='admin',method='GET',body,query={}}={},c=client()){const res=response();await load('lib/admin-perrun-production.js',c)({method,headers:token?{authorization:'Bearer '+token}:{},body,query},res);return res;}
for(const token of [null,'bad','user'])for(const method of ['GET','POST'])test('Production HTTP authorizes JWT admin before '+method+' for '+token,async()=>{const c=client();let calls=0;c.rpc=async()=>{calls++;throw Error('Denied request cannot query');};const r=await run({token,method},c);assert.equal(r.code,token==='user'?403:401);assert.equal(calls,0);});
test('HTTP create/close use trusted actor, revision and real RPC; CSV from closed snapshot',async()=>{const x=await f.paid(db),id=crypto.randomUUID();const draft=await run({method:'POST',body:{operation:'save',batchId:id,expectedRevision:null,registrationIds:[x.human.id]}});assert.equal(draft.code,200);assert.equal(draft.body.batch.created_by_user_id,f.actor);assert.equal(draft.body.batch.created_by_email,f.email);const closed=await run({method:'POST',body:{operation:'close',batchId:id,expectedRevision:0,confirm:true}});assert.equal(closed.code,200);assert.equal(closed.body.items[0].production_number,1);const csv=await run({query:{batchId:id,format:'csv'}});assert.equal(csv.code,200);assert.match(csv.headers['Content-Type'],/text\/csv/);assert.match(csv.body,/production_number/);assert.equal((await run({query:{batchId:id,format:'csv'}})).body,csv.body);});
for(const field of ['production_number','bib_number','admin_user_id','admin_email','snapshot','created_by_email'])test('HTTP rejects browser supplied '+field,async()=>{const r=await run({method:'POST',body:{operation:'save',batchId:crypto.randomUUID(),expectedRevision:null,registrationIds:[],[field]:'forged'}});assert.equal(r.code,400);assert.equal((await f.read(db)).batches.length,0);});
test('Close requires explicit confirmation, integer revision and cannot accept replacement membership',async()=>{for(const b of [{confirm:false},{confirm:true,expectedRevision:null},{confirm:true,registrationIds:[]}])assert.equal((await run({method:'POST',body:{operation:'close',batchId:crypto.randomUUID(),expectedRevision:0,...b}})).code,400);});
test('HTTP draft CSV refused, absent batch 404 and stale revision 409',async()=>{const x=await f.paid(db),b=await f.save(db,[x.human.id]);assert.equal((await run({query:{batchId:b.batch.id,format:'csv'}})).code,409);assert.equal((await run({query:{batchId:crypto.randomUUID()}})).code,404);assert.equal((await run({method:'POST',body:{operation:'close',batchId:b.batch.id,expectedRevision:1,confirm:true}})).code,409);});
test('RPC missing fails closed and caches disabled; unsupported method rejected',async()=>{const c=client();c.rpc=async()=>({error:{code:'PGRST202'}});const r=await run({},c);assert.equal(r.code,503);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal((await run({method:'DELETE'})).code,405);});
test('Admin Edit GET includes closed production status, stable batch and read-only number',async()=>{const x=await f.paid(db),b=await f.save(db,[x.human.id]);await f.close(db,b.batch.id);const res=response();await load('lib/admin-perrun-registration.js',client())({method:'GET',headers:{authorization:'Bearer admin'},query:{orderSessionId:x.orderId}},res);assert.equal(res.code,200);assert.equal(res.body.registration.production_status,'closed');assert.equal(res.body.registration.production_batch_id,b.batch.id);assert.equal(res.body.registration.production_number,1);});
test('Missing production table preserves existing Admin Edit with explicit not_available status',async()=>{const c=client(),base=c.from;c.from=table=>table==='perrun_production_items'?{select(){return this;},eq(){return this;},then(resolve){return Promise.resolve({error:{code:'42P01'}}).then(resolve);}}:base(table);const info=await require('../lib/_perrun-production').productionInfo(c,'cs_test_missing');assert.equal(info.production_status,'not_available');});
